### ISSUE TITLE
关于crazypeace/v2ray的问题

### ISSUE THREAD

**Issue by bk1412** [crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2#1]
4.27.0链接已经404，原项目没开issue，只能跑过来提交一下了

主机时间：
               Local time: Mon 2022-04-18 23:34:14 CST
                Time zone: Asia/Shanghai (CST, +0800)

 指定下载 V2Ray v4.27.0!!!
--2022-04-18 23:34:14--  https://github.com/v2fly/v2ray-core/releases/download/v4.27.0/v2ray-linux-arm64.zip
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-04-18 23:34:15 ERROR 404: Not Found.

         下载 V2Ray 失败啦..可能是你的 VPS 网络太辣鸡了...请重试...

**Comment by crazypeace** [comment]
你好！请问你是什么环境？哪里的VPS？

1. crazypeace/v2ray 那边我把issue开了。如果问题没有解决的话，麻烦你再提一次，不好意思。
2. 如果你有一定的脚本能力，求急的话，你打开 download-v2ray.sh 修改这一行下载链接
```
v2ray_download_link="https://github.com/v2fly/v2ray-core/releases/download/$v2ray_latest_ver/v2ray-linux-${v2ray_bit}.zip"
```
3. 你可以去 https://github.com/v2fly/v2ray-core/releases/tag/v4.27.0 找到对应的下载链接，你是arm64的话，找对应的链接就好了，将第2步中的链接写死。
4. 再次安装试试
```
cd /tmp/233boy/v2ray
./install.sh local
```

**Comment by crazypeace** [comment]
repo的修改更新我需要仔细检查一下再决定。

**Comment by bk1412** [comment]
> 你好！请问你是什么环境？哪里的VPS？
> 
> 1. crazypeace/v2ray 那边我把issue开了。如果问题没有解决的话，麻烦你再提一次，不好意思。
> 2. 如果你有一定的脚本能力，求急的话，你打开 download-v2ray.sh 修改这一行下载链接
> 
> ```
> v2ray_download_link="https://github.com/v2fly/v2ray-core/releases/download/$v2ray_latest_ver/v2ray-linux-${v2ray_bit}.zip"
> ```
> 
> 3. 你可以去 https://github.com/v2fly/v2ray-core/releases/tag/v4.27.0 找到对应的下载链接，你是arm64的话，找对应的链接就好了，将第2步中的链接写死。
> 4. 再次安装试试
> 
> ```
> cd /tmp/233boy/v2ray
> ./install.sh local
> ```

可以自己修改，想的是如果没有回应我就尝试自己修改一下，机器是新加坡区的甲骨文arm

**Comment by bk1412** [comment]
> 我对照了一下233boy的repo，已经更新了脚本。 你可以重新执行试试

好，问题已经解决了，半夜回复辛苦了，但是刚刚安装的时候还碰到个小问题，我去那边给你提一下issue

**Comment by bk1412** [comment]
问题解决，脚本更新
