### ISSUE TITLE
部署完成后caddy.service重启出错

### ISSUE THREAD

**Issue by biozzl** [crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2#6]
用的小鸡是HAX的./EU-OpenVZ， 也按照教程开启了Tun服务

Job for caddy.service failed because the control process exited with error code.
See "systemctl status caddy.service" and "journalctl -xe" for details.

INFO] Status check in progress...

 ----------------------------
 WireGuard      : Running
 IPv4 Network   : WARP
 IPv6 Network   : Normal
 ----------------------------

[INFO] Done.

重启 V2Ray
----------------------------------------------------------------

重启 CaddyV2
----------------------------------------------------------------
Job for caddy.service failed because the control process exited with error code.
See "systemctl status caddy.service" and "journalctl -xe" for details.

**Comment by biozzl** [comment]
ob for caddy.service failed because the control process exited with error code.
See "systemctl status caddy.service" and "journalctl -xe" for details.
root@1242932902hax:~# systemctl status caddy.service
● caddy.service - Caddy
     Loaded: loaded (/lib/systemd/system/caddy.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-09-22 04:24:56 PDT; 2min 55s ago
       Docs: https://caddyserver.com/docs/
    Process: 2360 ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile (code=exited, status=1/FAILURE)
   Main PID: 2360 (code=exited, status=1/FAILURE)
     Status: "loading new config: http app module: start: tcp: listening on :80: listen tcp :80: bind: address already in use"

Sep 22 04:24:56 1242932902hax.localdomain caddy[2360]: {"level":"info","ts":1663845896.6767423,"logger":"http","msg":"server is listen>
Sep 22 04:24:56 1242932902hax.localdomain caddy[2360]: {"level":"info","ts":1663845896.676982,"logger":"http","msg":"enabling automati>
Sep 22 04:24:56 1242932902hax.localdomain caddy[2360]: {"level":"info","ts":1663845896.6827066,"logger":"http","msg":"enabling HTTP/3 >
Sep 22 04:24:56 1242932902hax.localdomain caddy[2360]: {"level":"info","ts":1663845896.6843448,"logger":"http.log","msg":"server runni>
Sep 22 04:24:56 1242932902hax.localdomain caddy[2360]: {"level":"info","ts":1663845896.6852849,"logger":"tls.cache.maintenance","msg":>
Sep 22 04:24:56 1242932902hax.localdomain caddy[2360]: {"level":"info","ts":1663845896.6853025,"logger":"tls.cache.maintenance","msg":>
Sep 22 04:24:56 1242932902hax.localdomain caddy[2360]: Error: loading initial config: loading new config: http app module: start: tcp:>
Sep 22 04:24:56 1242932902hax.localdomain systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Sep 22 04:24:56 1242932902hax.localdomain systemd[1]: caddy.service: Failed with result 'exit-code'.
Sep 22 04:24:56 1242932902hax.localdomain systemd[1]: Failed to start Caddy.

**Comment by ykiZheng** [comment]
遇到了同样的问题，最后解决的方法是reboot后正常了
