### ISSUE TITLE
算了

### ISSUE THREAD

**Issue by raddyyt** [crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2#7]
算了

**Comment by crazypeace** [comment]
谢谢你的感谢！很高兴能帮到你！

关于 clash ，我自己是不用的。我觉得自建节点的，没有那么多节点要管理，就开个简单的v2rayN就行了。

如果用不惯新版本v2rayN的路由配置，那就用v2rayN-3.29的PAC模式好了，我弄了个小修改版，支持vless节点导入导出。
https://github.com/crazypeace/v2rayN-3.29-VLESS

关于Subconverter自建，你用google搜一下吧。我觉得应该有教程的。

关于vmess和vless的取舍，我是这么思考的。

1. vless链接格式没有加密，可以肉眼直接阅读，不管是脚本生成，还是人肉手动生成，都比较方便。在有人反馈问题的时候，帮忙查问题也容易拿到节点参数，不需要像vmess还要base64再解一遍码。
2. 放到了tls里面，并不影响安全性。
3. 实在要用vmess的用户，改一个字母就行了。自己再学习一下节点参数分别是什么意思，往自己的翻墙工具里面填就是了。如果觉得这个操作过程和学习麻烦的，那就不要用vmess了，或者不要用我的脚本。

我只是业余做这个事情，所以在技术方案上要考虑开发的复杂程度，也要考虑维护的复杂程度。

更进一步的，我还想考虑大家学习的复杂程度。我很希望大家有自己的需求的时候就fork一份，自己改。

**Comment by crazypeace** [comment]
脚本更新了一下，最后一步提示是否切换到Vmess协议。
你可以试用看看。
如果你想fork了改成自己的Vmess脚本，基本上裁剪一下就可以了。
希望能帮到你。:)

**Comment by raddyyt** [comment]
谢谢, 没想到过了这么久会有回复, 但我已经放弃研究脚本了, 成型的脚本太封闭了, 一个作者一个思路, 都只适合自己, 很难搭配整合, 就像我用这个脚本安装V2ray可以运行的很好, 但是里面配的是caddy, 而我在网上找的能在IPv6上运行Subconverter的都是用的Nginx, 装完了一直都不能正常运行, 我这种新手压根就搞不懂他俩的具体区别, 能不能搭配, 找人问也都是"我的东西按我自己想法运行, 别的能不能适配跟我没关系"的态度, 一盆盆冷水浇的我放弃了.  直到前几天偶然接触了一些宝塔面板的攻略, 才发现还是图形化操作更容易理解, 我只用了2天就把之前半个多月都搞不定的东西全都安装好了. 以后遇到问题我也会优先找用面板解决的攻略了

**Comment by raddyyt** [comment]
另外说一下关于clash, 个人认为跟v2rayN比,它的优势并不是管理节点,而是方便整合订阅各种去广告规则和自己添加的例外规则, github上就有很多人提供各种去广告,阻止获取隐私等等的配置规则,把链接放到自己的config文件里,用subconverter调用转换一下订阅链接就可以跟着作者实时更新, 这方面的方便性是v2ray系软件没有的, 我两个软件都有装, 但还是Clash用的多,适用范围更广些, 这就注定了在Clash彻底支持Vless之前Vmess是不可替代的

**Comment by crazypeace** [comment]
很高兴你找到了使用面板这一条适合自己的路。
你喜欢鼠标多点几次，那也有人喜欢一行命令执行下去就不管了。
你提到"我的东西按我自己想法运行, 别的能不能适配跟我没关系"，这是开源世界里的常态。
要么你去付费的世界里，用钱实现你的要求。要么在开源的世界里把自己变成创作者，自己实现自己的要求。

Nginx和Caddy都是网站服务器，你把这两个学懂了之后，既可以把v2ray和Subconverter都部署在Caddy上，也可以都部署在Nginx上。你还可以开自己的Repo向大家宣传你的学习成果。

你愿意用Clash的去广告规则没问题啊。我自己的使用习惯和使用场景，v2rayN 3.29足够了。开源的世界里，人是自由的。
就像你在Clash里用谁的规则，添加自己的规则，都是完全自由的。当你遇到两个作者的规则互相冲突的时候，你一样会遇到"我的东西按我自己想法运行, 别的能不能适配跟我没关系"的回应的。
